spring.application.name=votaya-backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/votaya
spring.datasource.username=root
spring.datasource.password=VIRUZ70CH

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secreto=${JWT_SECRETO:Jy/BAL8AVg/Qoo4qi+XIY+k/staPvf0UZPAtisD5KTQbGmEWxTmkwHIQEaPsscdZhSoGDS2QZUjZYielMQbICg==}
jwt.expiracion-milisegundos=86400000

spring.flyway.enabled=false